name: prime_social_media_flutter_ui_kit
description: Prime Social Media Flutter UI Kit
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
# Flutter Version: 3.32.0
# Dart Version: 3.8.0
version: 1.0.2

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.7.2
  story_view: ^0.16.0
  http: ^1.4.0
  fluttertoast: ^8.2.12
  video_player: ^2.9.5
  camera: ^0.10.5+9
  image_picker: ^1.1.2
  chewie: ^1.10.0
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  flutter_barcode_scanner_plus: ^3.0.8
  share_plus: ^11.0.0
  path_provider: ^2.1.5
  photofilters: ^3.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/videos/
    - assets/gif/

  fonts:
    - family: SegoeUI_Regular
      fonts:
        - asset: assets/fonts/SegoeUI.ttf
    - family: SegoeUI_SemiBold
      fonts:
        - asset: assets/fonts/SegoeUI-SemiBold.ttf
    - family: SegoeUI_Bold
      fonts:
        - asset: assets/fonts/SegoeUI-Bold.ttf
    - family: Sevillana_Regular
      fonts:
        - asset: assets/fonts/Sevillana-Regular.ttf
