// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2h73Z7Gfg_rY_8Zgi_m6wQsaSZUYMaIQ',
    appId: '1:577561851476:web:67b52c70ab87aa8efa9fc1',
    messagingSenderId: '577561851476',
    projectId: 'sportme-e47cd',
    authDomain: 'sportme-e47cd.firebaseapp.com',
    storageBucket: 'sportme-e47cd.firebasestorage.app',
    measurementId: 'G-EKF0BBJ8FM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAFR9HF4FdEhujDpQ0Ak9b5D0yGStBHyk',
    appId: '1:577561851476:android:379eb54a2ff6a606fa9fc1',
    messagingSenderId: '577561851476',
    projectId: 'sportme-e47cd',
    storageBucket: 'sportme-e47cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhsKZCybicYribhQsTJAVO1MVJoFRvNTY',
    appId: '1:577561851476:ios:870cfba814adc91afa9fc1',
    messagingSenderId: '577561851476',
    projectId: 'sportme-e47cd',
    storageBucket: 'sportme-e47cd.firebasestorage.app',
    iosBundleId: 'com.example.primeSocialMediaFlutterUiKit',
  );
}
